version: '3.8'

services:
  gitea-check-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GITEA_URL=${GITEA_URL}
      - TOKEN=${TOKEN}
      - PORT=8080
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s